export const surpriseMePrompts = [
  'a cybernetic garden where flowers bloom with digital code instead of pollen',
  'a mystical forest where trees grow upside down, their roots reaching for the sky',
  'a steampunk metropolis inhabited by clockwork creatures',
  'an underwater city filled with bioluminescent jellyfish skyscrapers',
  'a floating island powered by giant propellers, drifting through the clouds',
  'a celestial library where stars are books and constellations tell stories',
  'a futuristic train station where time-traveling locomotives depart to different eras',
  'a desert oasis guarded by mechanical dragons',
  'a cosmic dance party on the rings of Saturn, attended by aliens from across the galaxy',
  'a neon-lit cyberpunk alley where street vendors sell holographic snacks',
  'a surreal landscape where mountains are made of crystal and rivers flow with liquid gold',
  'an enchanted castle hidden within a labyrinth of rainbow-colored clouds',
  'a post-apocalyptic world reclaimed by nature, with skyscrapers covered in vines',
  'a floating market in the sky where airships trade exotic goods',
  'a psychedelic journey through the mind of a quantum physicist, depicted as a swirling vortex of colors',
  'a parallel universe where gravity works sideways, and people walk on walls instead of floors',
  'an intergalactic highway stretching across the cosmos, lined with cosmic rest stops',
  'a garden of mechanical flowers that bloom with sparks and gears',
  'a cityscape where buildings are made of living crystal, reflecting the colors of the rainbow',
  'a time-traveling pirate ship sailing through the corridors of time, collecting treasures from different epochs',
  'an ancient temple hidden deep in the jungle, guarded by robotic guardians',
  'a lunar colony where astronauts ride giant lunar rovers across the moon\'s surface',
  'a space station shaped like a giant, rotating Rubik\'s cube',
  'a dystopian future where cities are domed to protect against pollution, and airships soar above the smog',
  'a virtual reality nightclub where patrons can dance with holographic avatars of famous historical figures',
  'a crystal cavern illuminated by bioluminescent fungi, inhabited by glowing creatures',
  'a cosmic carnival on the edge of the universe, with rides that defy the laws of physics',
  'a garden of glass flowers that change color with the phases of the moon',
  'a city skyline where skyscrapers are adorned with intricate clockwork mechanisms',
  'an underwater graveyard of ancient ships, inhabited by merfolk and sea monsters'
];
