import React, { useEffect, useState } from 'react';
import { Card, FormField, Loader } from '../components';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faFacebook, faInstagram, faTwitter } from '@fortawesome/free-brands-svg-icons';
import { faImage, faPaintBrush, faCube, faFilm, faBullhorn, faChalkboard } from '@fortawesome/free-solid-svg-icons';
import image1 from '../assets/images/ai-generated-8631634_1280.jpg';
import image2 from '../assets/images/pexels-tara-winstead-8386440.jpg'
import image3 from '../assets/images/woman-7533430_1280.jpg'
import image4 from '../assets/images/astranaut-img.jpg'
import { logo } from '../assets';
const Home = () => {
  const [currentImageIndex, setCurrentImageIndex] = useState(0);
  const images = [image1, image2, image3];

  useEffect(() => {
    const interval = setInterval(() => {
      setCurrentImageIndex((prevIndex) => (prevIndex + 1) % images.length);
    }, 3000); // Change image every 3 seconds

    return () => clearInterval(interval); // Cleanup interval on component unmount
  }, [images.length]);

  return (
    <section className="">
      {/* Carousel section */}
      <section className='crousal-section flex justify-center' style={{ backgroundImage: `url(${images[currentImageIndex]})`, backgroundSize: 'cover', backgroundPosition: 'center', backgroundRepeat: 'no-repeat' }}>
        <div className='text-center mt-8'>
          <h1 className="font-extrabold text-[#fefeff] text-[32px] mt-12">The Community Showcase</h1>
          <p className="mt-2 text-center text-[#666e75] text-[14px]">Browse through a collection of imaginative and visually stunning images generated by DALL-E AI</p>
          <div className='home-btn mt-2'>
            <a href="/signin">
              <button className="dark:bg-cyan-700 dark:border-cyan-600 border-cyan-100 dark:hover:bg-black hover:bg-black font-semibold mb-2 items-center justify-center rounded-full border-2 bg-white py-2 px-8 text-center transition-all hover:border-transparent hover:text-white dark:text-white dark:hover:border-transparent uppercase cursor-pointer">
                Join Us
              </button>
            </a>
          </div>
        </div>
      </section>

      <section>
        <div className="flex justify-between justify-evenly mt-6 flex-col sm:flex-row">
          <div className="card1 mt-6 sm:mt-0">
            <div className="max-w-xs mx-auto overflow-hidden shadow-lg rounded-lg bg-black text-white">
              <div className="relative overflow-hidden">
                {/* Image with hover effect */}
                <img
                  className="w-full h-52 transition-transform duration-500 transform hover:scale-105"
                  src={image1}
                  alt="Image"
                />
              </div>
              <div className="px-4 py-2">
                {/* Title */}
                <h3 className="text-white font-semibold text-lg mb-2">An vehicle in beautiful area</h3>
                {/* Description */}
                <p className="text-white text-sm">
                In a towering castle constructed entirely of stacked books, open pages serve as intricate turrets             </p>
              </div>
            </div>

          </div>
          <div className="card1 mt-6 sm:mt-0">
            <div className="max-w-xs mx-auto overflow-hidden shadow-lg rounded-lg bg-black text-white">
              <div className="relative overflow-hidden">
                {/* Image with hover effect */}
                <img
                  className="w-full transition-transform duration-500 transform hover:scale-105"
                  src={image2}
                  alt="Image"
                />
              </div>
              <div className="px-4 py-2">
                {/* Title */}
                <h3 className="text-white font-semibold text-lg mb-2">An robotic hand busy </h3>
                {/* Description */}
                <p className="text-white text-sm">
                An otherworldly cityscape emerges, its skyscrapers crafted from colossal crystals that refract and reflect the sunlight, creating a mesmerizing spectacle.                </p>
              </div>
            </div>

          </div>
          <div className="card1 mt-6 sm:mt-0">
            <div className="max-w-xs mx-auto overflow-hidden shadow-lg rounded-lg bg-black text-white">
              <div className="relative overflow-hidden">
                {/* Image with hover effect */}
                <img
                  className="w-full transition-transform duration-500 transform hover:scale-105"
                  src={image3}
                  alt="Image"
                />
              </div>
              <div className="px-4 py-2">
                {/* Title */}
                <h3 className="text-white font-semibold text-lg mb-2">A girl in foreast</h3>
                {/* Description */}
                <p className="text-white text-sm">
                Beneath the waves lies a whimsical underwater kingdom, where coral reefs take on the appearance of intricate castles, their spires reaching toward the surface as if seeking the warmth of the sun.                 </p>
              </div>
            </div>

          </div>
        </div>
      </section>
      <section className='article-ai mt-4'>
        <div className='prompt-img flex flex-col sm:flex-row justify-between justify-evenly gap-6  bg-black p-6  mt-6'>
          <div className='text-part bg-black rounded-lg shadow-lg p-6 border-sky-100 text-white ml-6 mr-3'>
            <h1 className="font-serif text-3xl font-bold mb-4">Text To Image Generation Using DALL-E 2.0</h1>
            <p className="font-sans text-lg">
              DALL-E 2.0 is an advanced AI model developed by OpenAI, designed to generate high-quality images based on textual descriptions. Leveraging cutting-edge techniques in deep learning and natural language processing, DALL-E 2.0 builds upon its predecessor's capabilities to produce even more diverse and realistic images from textual prompts.

              One of the key innovations of DALL-E 2.0 is its ability to understand and interpret complex textual descriptions with greater nuance and context. By analyzing the semantics and relationships within the input text, the model can generate images that accurately reflect the intended concepts and ideas conveyed in the prompt.
            </p>
            <br />
            <br />
            <p className='font-sans text-lg'>
              With its remarkable ability to synthesize images from textual input, DALL-E 2.0 has a wide range of potential applications across different domains, including design, art, fashion, storytelling, and more. From generating concept art and illustrations to creating visual prototypes and enhancing creative workflows, DALL-E 2.0 empowers users to explore new possibilities and push the boundaries of image generation technology.
            </p>
          </div>
          <div className='image-prompt-part bg-gray-800 rounded-lg shadow-lg p-6 text-white mr-6'>
            <h1 className="font-serif text-3xl font-bold mb-4">Prompt:</h1>
            <p className="font-sans text-lg">An robotic hand busy in wotking the projects.</p>
            <div className="relative overflow-hidden mt-4">
              {/* Image with hover effect */}
              <img
                className="w-full transition-transform duration-500 transform hover:scale-105"
                src={image2}
                alt="Image"
              />

            </div>
          </div>
        </div>
      </section>

      <section className='description-section bg-black mt-12'>
        <h1 className='text-4xl font-bold text-center pt-4 text-white'>Services</h1>
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-6 pt-20 pl-6 pr-6 pb-20">
          {/* Grid Item 1 */}
          <div className="grid-item bg-gray-800 text-white transition-colors duration-300 hover:bg-cyan-200 hover:text-black rounded-lg p-4">
            <FontAwesomeIcon icon={faImage} size="2x" />
            <h3 className='text-2xl font-bold mt-2'>
              Image Synthesis</h3>
            <p>DALL-E 2.0 generates high-quality images from textual descriptions, enabling diverse visual outputs ranging from realistic scenes to abstract concepts.</p>
          </div>

          {/* Grid Item 2 */}
          <div className="grid-item bg-gray-800 text-white transition-colors duration-300 hover:bg-cyan-200 hover:text-black rounded-lg p-4">
            <FontAwesomeIcon icon={faPaintBrush} size="2x" />
            <h3 className='text-2xl font-bold mt-2'>Conceptual Art Creation</h3>
            <p>Leveraging its understanding of language and visual concepts, DALL-E 2.0 assists in the creation of conceptual art pieces, translating textual prompts into visually compelling artworks.</p>
          </div>

          {/* Grid Item 3 */}
          <div className="grid-item bg-gray-800 text-white transition-colors duration-300 hover:bg-cyan-200 hover:text-black rounded-lg p-4">
            <FontAwesomeIcon icon={faCube} size="2x" />
            <h3 className='text-2xl font-bold mt-2'>Product Design Visualization</h3>
            <p>DALL-E 2.0 aids in visualizing product designs by transforming textual specifications into photorealistic renderings, facilitating the exploration of design.</p>
          </div>

          {/* Grid Item 4 */}
          <div className="grid-item bg-gray-800 text-white transition-colors duration-300 hover:bg-cyan-200 hover:text-black rounded-lg p-4">
            <FontAwesomeIcon icon={faFilm} size="2x" />
            <h3 className='text-2xl font-bold mt-2'>Storyboarding Assistance</h3>
            <p>
              By interpreting narrative descriptions, DALL-E 2.0 assists in storyboarding processes, generating visual sequences that depict scenes, characters, and plot developments.
            </p>
          </div>

          {/* Grid Item 5 */}
          <div className="grid-item bg-gray-800 text-white transition-colors duration-300 hover:bg-cyan-200 hover:text-black rounded-lg p-4">
            <FontAwesomeIcon icon={faBullhorn} size="2x" />
            <h3 className='text-2xl font-bold mt-2'>Branding and Marketing Imagery:</h3>
            <p>DALL-E 2.0 contributes to branding and marketing efforts by producing customized visual content, including logos, advertisements, and promotional materials.</p>
          </div>

          {/* Grid Item 6 */}
          <div className="grid-item bg-gray-800 text-white transition-colors duration-300 hover:bg-cyan-200 hover:text-black rounded-lg p-4">
            <FontAwesomeIcon icon={faChalkboard} size="2x" />
            <h3 className='text-2xl font-bold mt-2'>Educational Visual Aids</h3>
            <p>Supporting educational endeavors, DALL-E 2.0 generates visual aids such as diagrams, illustrations, and infographics based on textual input.</p>
          </div>
        </div>


      </section>
      <div className='bg-white mt-4'>
        <div className='curve'>
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320"><path fill="#000000" fill-opacity="1" d="M0,64L480,160L960,224L1440,192L1440,320L960,320L480,320L0,320Z"></path></svg>
        </div>
      </div>
      <footer className="bg-black py-8 px-6">
        <div className="max-w-7xl mx-auto flex flex-col sm:flex-row pb-4 justify-between gap-9 justify-around items-center">
          <div className='logo'>
            <a href="/">
              <img src={logo} alt="logo" className="w-32 ml-2 object-contain bg-white py-6 px-4" />
            </a>
          </div>
          <div className="space-x-4">

            <a href="#" className="text-white justify-between flex mt-2 hover:text-gray-400 transition-colors duration-300">
              <FontAwesomeIcon icon={faFacebook} size="2x" />
              <h1>Facebook</h1>
            </a>
            <a href="#" className="text-white justify-between flex mt-2 hover:text-gray-400 transition-colors duration-300">
              <FontAwesomeIcon icon={faInstagram} size="2x" />
              <h1 className='ml-4'>Instagram</h1>
            </a>
            <a href="#" className="text-white justify-between flex mt-2 hover:text-gray-400 transition-colors duration-300">
              <FontAwesomeIcon icon={faTwitter} size="2x" />
              <h1>Twitter</h1>
            </a>
          </div>
          {/* Email subscription */}
          <div className="mt-4 flex">

            <div className="flex-grow">
              <input type="email" className="w-full px-4 py-2 rounded-l-lg focus:outline-none" placeholder="Your email address" />
            </div>
            <div>
              <button className="bg-red-500 hover:bg-black text-white px-6 py-2 rounded-r-lg transition-colors duration-300">
                Subscribe
              </button>
            </div>
          </div>
        </div>
        <hr />
        <div className="copyright text-center pt-3 text-white">
          <p>&copy; 2024 Your Company Name. All rights reserved.</p>
        </div>
      </footer>

    </section>


  );
};

export default Home;
